In [1]:
from jqdatasdk import *

#auth('18613838075','ASdf@123')

auth('13810783511','123456Ning')

提示：当前环境 pandas 版本高于 0.25，get_price 与 get_fundamentals_continuously 接口 panel 参数将固定为 False
注意：0.25 以上版本 pandas 不支持 panel，如使用该数据结构和相关函数请注意修改
auth success

In [2]:
get_query_count()

{'total': 200000000, 'spare': 196964045}

In [3]:
etf_list_df = get_all_securities(types=['etf'])
etf_list_df.to_csv('./csv_files/etf.csv')

In [4]:
ret = get_bars('159915.XSHE', 10, '1d')
ret

         date   open   high    low  close
0  2021-05-27  3.086  3.135  3.066  3.118
1  2021-05-28  3.117  3.175  3.099  3.121
2  2021-05-31  3.130  3.200  3.130  3.195
3  2021-06-01  3.180  3.200  3.136  3.188
4  2021-06-02  3.200  3.202  3.120  3.133
5  2021-06-03  3.129  3.149  3.094  3.099
6  2021-06-04  3.077  3.177  3.077  3.141
7  2021-06-07  3.136  3.136  3.092  3.122
8  2021-06-08  3.118  3.170  3.082  3.105
9  2021-06-09  3.096  3.120  3.079  3.100

In [14]:
import datetime
import numpy as np

code = '399324.XSHE'

etf_df = get_price(code, start_date='2006-01-24', end_date=datetime.date.today(), fq=None)

etf_df.dropna(inplace=True)

etf_df['volume'] = etf_df['volume'].astype(np.int64)
etf_df['money'] = etf_df['money'].astype(np.int64)
etf_df.index.name='date'


etf_df.to_csv('./csv_files/{}.csv'.format(code))
etf_df.head()

               open    close     high      low     volume       money
date
2006-01-24  1254.79  1257.13  1272.04  1248.13  421309300  2304194478
2006-01-25  1256.80  1270.83  1271.64  1254.43  394086900  2111031633
2006-02-06  1275.09  1324.32  1325.13  1275.09  462304500  2578183279
2006-02-07  1327.61  1318.64  1336.31  1302.74  529257500  3036951828
2006-02-08  1316.27  1315.31  1317.50  1301.26  332006700  1817257749

In [ ]:
etf_code = 159915
ret = get_price('{}.XSHE'.format(etf_code), start_date='2020-05-07', end_date='2020-06-01', fq=None)
ret.dropna(inplace=True)
ret

In [ ]:
import pymongo
import datetime

client = pymongo.MongoClient('mongodb://localhost:27017/')
db = client['stock_etf']

In [ ]:
# the df to insert
df2insert = ret

doclist = []
for idx,row in df2insert.iterrows():
    doclist.append(
        dict(
            date=datetime.datetime.combine(row.name.date(),datetime.time()),
            open=float(row['open']),
            high=float(row['high']),
            low=float(row['low']),
            close=float(row['close']),
            volume=int(row['volume']),
        )
    )


collection = db['etf_'+str(etf_code)]
collection.create_index([('date', pymongo.ASCENDING)], unique=True)
res = collection.insert_many(doclist)
res

In [ ]:
db.list_collection_names()

In [ ]:
collection = db['etf_159915']
for i in collection.find().sort('date',pymongo.DESCENDING).limit(3):
    print(i)
#datetime.date.today()

In [ ]:
collection.count_documents({})

In [ ]:
get_all_securities(types=['index'], date=None)

In [ ]:
ret = get_price('000300.XSHG', start_date='2020-05-07', end_date='2020-06-01', fq=None)
ret

In [4]:
from jqdatasdk import finance
q = query(finance.STK_INCOME_STATEMENT).filter(
        finance.STK_INCOME_STATEMENT.code=='000783.XSHE',              #选定股票  000783.XSHE
        finance.STK_INCOME_STATEMENT.end_date > '2005-01-01',          #指定查询时间段大于2005年1月1日
        finance.STK_INCOME_STATEMENT.end_date < '2018-01-01',          #指定查询时间段小于2018年1月1日
        finance.STK_INCOME_STATEMENT.net_profit <0,                    #指定查询到的数据中net_profit为负
        finance.STK_INCOME_STATEMENT.report_type == 0,                 #指定报告期类型为本期
        ).order_by(finance.STK_INCOME_STATEMENT.end_date.desc()  ).limit(5)   #根据end_date降序排序,并返回前5条数据 
finance.run_query(q)

,id,company_id,company_name,code,a_code,b_code,h_code,pub_date,start_date,end_date,...,non_current_asset_disposed,other_earnings,rd_expenses,asset_deal_income,sust_operate_net_profit,discon_operate_net_profit,credit_impairment_loss,net_open_hedge_income,interest_cost_fin,interest_income_fin
0,257078,430000783,长江证券股份有限公司,000783.XSHE,000783,None,None,2007-10-22,2007-01-01,2007-09-30,...,None,None,None,None,None,None,None,None,None,None
1,257070,430000783,长江证券股份有限公司,000783.XSHE,000783,None,None,2006-10-25,2006-01-01,2006-09-30,...,None,None,None,None,None,None,None,None,None,None
2,257068,430000783,长江证券股份有限公司,000783.XSHE,000783,None,None,2006-08-17,2006-01-01,2006-06-30,...,None,None,None,None,None,None,None,None,None,None
3,257066,430000783,长江证券股份有限公司,000783.XSHE,000783,None,None,2006-04-29,2006-01-01,2006-03-31,...,None,None,None,None,None,None,None,None,None,None
4,257064,430000783,长江证券股份有限公司,000783.XSHE,000783,None,None,2006-04-29,2005-01-01,2005-12-31,...,None,None,None,None,None,None,None,None,None,None

In [12]:
q = query(
    valuation
).filter(
#     valuation.code == '000001.XSHG'
    valuation.code.in_(['510300.XSHG', '159915.XSHE'])
)

df = get_fundamentals(q, '2019-06-15')

df

Empty DataFrame
Columns: [id, code, pe_ratio, turnover_ratio, pb_ratio, ps_ratio, pcf_ratio, capitalization, market_cap, circulating_cap, circulating_market_cap, day, pe_ratio_lyr]
Index: []